"use client";

import { useState } from "react";
import { Leaf, Sparkles, Cpu, ArrowRight } from "lucide-react";
import { analyze } from "../actions/orchestrate";
import { UploadPanel } from "../components/UploadPanel";
import { FootprintSummary } from "../components/FootprintSummary";
import { HotspotCard } from "../components/HotspotCard";
import type { Report } from "../lib/types";

export default function Home() {
  const [csv, setCsv] = useState("");
  const [periodLabel, setPeriodLabel] = useState("July 2026");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [report, setReport] = useState<Report | null>(null);
  const [mode, setMode] = useState<"flow" | "heuristic" | null>(null);

  async function handleLoadExample() {
    setError(null);
    try {
      const res = await fetch("/sample-usage.csv");
      setCsv(await res.text());
    } catch {
      setError("Could not load the example file.");
    }
  }

  async function handleAnalyze() {
    setLoading(true);
    setError(null);
    try {
      const result = await analyze({ usageCsv: csv, periodLabel });
      if (result.ok) {
        setReport(result.data);
        setMode(result.mode);
      } else {
        setError(result.error);
        setReport(null);
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong.");
      setReport(null);
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="min-h-screen mx-auto max-w-5xl px-4 py-8 sm:py-12">
      {/* Header */}
      <header className="mb-8">
        <div className="flex items-center gap-2.5">
          <div className="flex h-9 w-9 items-center justify-center rounded-[var(--radius-sm)] bg-accent-soft border border-accent/30">
            <Leaf className="w-5 h-5 text-accent" />
          </div>
          <div>
            <h1 className="text-lg font-semibold text-ink leading-tight">Cloud Carbon Advisor</h1>
            <p className="text-xs text-muted">Git blame for your cloud carbon.</p>
          </div>
          {mode && (
            <span
              className={`ml-auto inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] ${
                mode === "flow"
                  ? "border-accent/30 bg-accent-soft text-accent"
                  : "border-edge bg-panel-2 text-muted"
              }`}
              title={
                mode === "flow"
                  ? "Diagnoses & recommendations generated by your deployed Lamatic flow."
                  : "No Lamatic flow configured — showing the deterministic offline heuristic plan. Set LAMATIC_CARBON_ADVISOR_FLOW_ID to enable the LLM."
              }
            >
              {mode === "flow" ? <Sparkles className="w-3 h-3" /> : <Cpu className="w-3 h-3" />}
              {mode === "flow" ? "Lamatic flow" : "offline heuristic"}
            </span>
          )}
        </div>
      </header>

      <div className="space-y-6">
        <UploadPanel
          csv={csv}
          onCsvChange={setCsv}
          periodLabel={periodLabel}
          onPeriodChange={setPeriodLabel}
          onAnalyze={handleAnalyze}
          onLoadExample={handleLoadExample}
          loading={loading}
          error={error}
        />

        {!report && !loading && (
          <section className="rounded-[var(--radius)] border border-dashed border-edge-strong bg-panel/30 p-8 text-center">
            <div className="mx-auto mb-3 flex h-11 w-11 items-center justify-center rounded-full bg-accent-soft">
              <Leaf className="w-5 h-5 text-accent" />
            </div>
            <p className="text-sm text-ink font-medium">Turn a usage export into a carbon plan</p>
            <p className="mx-auto mt-1.5 max-w-md text-xs text-muted leading-relaxed">
              Every gram is computed by code from published grid-intensity and energy factors — the
              model only decides <em>which lever to pull</em>, never the numbers. Press{" "}
              <span className="text-accent">Load example</span> then{" "}
              <span className="text-accent">Analyze</span> to see it.
            </p>
          </section>
        )}

        {report && (
          <>
            <FootprintSummary report={report} />

            {report.hotspots.length > 0 ? (
              <section>
                <div className="mb-3 flex items-center gap-2">
                  <ArrowRight className="w-4 h-4 text-accent" />
                  <h2 className="text-sm font-semibold text-ink">
                    Carbon hotspots &amp; decarbonization plan
                  </h2>
                  <span className="text-xs text-muted-2">
                    {report.hotspots.length} ranked by impact
                  </span>
                </div>
                <div className="space-y-4">
                  {report.hotspots.map((h, i) => (
                    <HotspotCard key={h.id} hotspot={h} rank={i + 1} />
                  ))}
                </div>
              </section>
            ) : (
              <p className="text-sm text-muted">No hotspots cleared the significance floor for this period.</p>
            )}

            <footer className="pt-2 text-center text-[11px] text-muted-2">
              Estimates use the Cloud Carbon Footprint methodology. Figures are planning-grade, not
              audited emissions. See the README for sources and limitations.
            </footer>
          </>
        )}
      </div>
    </main>
  );
}
